name: Build and Deploy Android
on:
  push:
    branches:
      - flutterflow
jobs:
  build-and-deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject Google Maps meta-data
        run: |
          sed -i 's|android:requestLegacyExternalStorage="true"|android:requestLegacyExternalStorage="true">\n        <meta-data android:name="com.google.android.geo.API_KEY" android:value="MAPS_API_KEY_PLACEHOLDER"/|' android/app/src/main/AndroidManifest.xml

      - name: Update Kotlin version
        run: |
          sed -i 's/org.jetbrains.kotlin.android" version "[^"]*"/org.jetbrains.kotlin.android" version "2.1.0"/' android/settings.gradle

      - name: Show AndroidManifest
        run: cat android/app/src/main/AndroidManifest.xml

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Inject Google Maps API Key
        env:
          MAPS_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          sed -i "s|MAPS_API_KEY_PLACEHOLDER|$MAPS_KEY|g" android/app/src/main/AndroidManifest.xml
          
          if grep -q "MAPS_API_KEY_PLACEHOLDER" android/app/src/main/AndroidManifest.xml; then
            echo "Error: El placeholder no fue reemplazado."
            exit 1
          else
            echo "API Key inyectada correctamente."
          fi

      - name: Verify AndroidManifest
        run: xmllint --noout android/app/src/main/AndroidManifest.xml

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Package APK
        run: |
          mkdir -p out
          cp build/app/outputs/flutter-apk/app-release.apk out/ || true

      - name: Deploy Android build
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/garsau/NearMe-Android mobile-repo
          rm -rf mobile-repo/*
          cp out/app-release.apk mobile-repo/ || true
          cd mobile-repo
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy Android build: $(date +'%Y-%m-%d %H:%M')"
          git push
